### ISSUE TITLE
Reduct Logo

### ISSUE THREAD

**Issue by Inkdpixels** [reduct/discussions#1]
We should decide and create logos for the reduct organization - I've been playing with this lately:
![2015-07-19](https://cloud.githubusercontent.com/assets/1557092/8803506/7f576cb6-2fc7-11e5-8821-761909061494.png)

@akoenig @grebaldi

**Comment by Inkdpixels** [comment]
Another try:
![reduct](https://cloud.githubusercontent.com/assets/1557092/8810801/daa8bab4-2ff1-11e5-9b35-a05c8df89b75.png)

And for packages:
![reduct-assembler](https://cloud.githubusercontent.com/assets/1557092/8810805/df6dac8a-2ff1-11e5-9c1e-440a46cf64be.png)

**Comment by akoenig** [comment]
w00t, w00t. I really like the second logo with it's variant. Great work @Inkdpixels. :)

Have you checked how the blip works in lower dimensions?

**Comment by Inkdpixels** [comment]
Thanks - glad you like it! Regarding the icon, here is a 50x50px version - I think we won't go lower anyway. :)

![reduct-icon](https://cloud.githubusercontent.com/assets/1557092/8811200/a9793380-2ff4-11e5-873d-600ab1a24154.png)

**Comment by akoenig** [comment]
Perfect! :)
