### ISSUE TITLE
Package names

### ISSUE THREAD

**Issue by Inkdpixels** [reduct/discussions#2]
Regarding the existing packages @akoenig and myself had a discussion today.

We both came to the conclusion that all packages should have a short and rememberable name, so the `ComponentDomParser` for example definitely needs a rebrand. @akoenig proposed `assembler` which I really dig(Even though it has a connection with the language itself)! So thumbs up for that!

Regarding the `NodeProto` - I am unsure about that one at the moment, I think if we scope the packages under the organization name f.e. `@reduct/assembler` we could just name it `component`.

What are your thoughts about that @grebaldi @akoenig ?

**Comment by akoenig** [comment]
Hehe ... I proposed `assemble`, but I guess that a noun might be a better fit. So thumbs up for `assembler`. I doubt that there is any collision with the low-level language. :)

Because of the package namespace, I really like `component` for `NodeProto`.

**Comment by grebaldi** [comment]
Actually I've written a pretty long text just a few minutes ago, but I realized, that I didn't like my ideas :D 

I'm fine with `component`, but somehow can't cope with `assembler`. Maybe something like `dominjector` might be kind of appropriate... 

Or maybe `weaver`? Perhaps too much adobe/macromedia in there...

**Comment by Inkdpixels** [comment]
`weaver` sounds good, but I miss something badass in there. Can we mix some explosions and gunshots or the like into the name?

Joke besides... Some more suggestions for the parser came into my mind:

`dispenser` -> Sounds good to me, but has some negativity in it doesn't it?
`assigner` -> Fits the most imho.
`allocator` -> Still alright.
`conductor` -> Meh?!

**Comment by akoenig** [comment]
`assigner` sounds pretty solid. +1 for that.

I throw two more suggestions into the ring:

`runtime` because it actually represents what the thingy is doing. It is responsible for "starting/mounting" the components.

or `engine` or `motor` or `boost` :)

EDIT: argh, smartphone's auto-correct is the worst!

**Comment by grebaldi** [comment]
Bootstrap?

damn you twitter... But actually a solid name, that's used in other framework contexts too... 

`runner` would be another thing maybe...

**Comment by radandt** [comment]
What about ComponentDistributor?

**Comment by grebaldi** [comment]
For the record: A gave up on the name thing today :) So, I'm okay with `assembler`, since I don't want this discussion block us moving forward.

**Comment by Inkdpixels** [comment]
Sorry @radandt - I already moved all repositories to the organization.

ComponentDomParser is now available on: https://github.com/reduct/assembler
NodeProto is now available on: https://github.com/reduct/component
