### ISSUE TITLE
New Package: Validators

### ISSUE THREAD

**Issue by Inkdpixels** [reduct/discussions#7]
As discussed in https://github.com/reduct/component/issues/15 - We should separate the propType validators from the Component. Any name suggestions here?

Maybe reduct/validity?

@grebaldi @akoenig

**Comment by grebaldi** [comment]
reduct/nitpick ^^

**Comment by akoenig** [comment]
w00t `nitpick`. It's awesome!

**Comment by Inkdpixels** [comment]
Sounds great! Will create the repository now! :+1:
